services:
  crewai:
    build:
      context: .
      dockerfile: Dockerfile.crewai
    container_name: qcyber_crewai
    restart: always
    env_file:
      - .env
  
  ollama:
    image: ollama/ollama:latest
    container_name: qcyber_ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mysql:
    image: mysql:9.4.0
    container_name: qcyber_mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql_volume:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    