services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qcyber_flask_api
    restart: always
    env_file:
      - .env
    ports:
      - "${FLASK_API_PORT:?error}:${FLASK_API_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - qcyber-network
  ollama:
    profiles: ["ollama"]
    image: ollama/ollama:latest
    container_name: qcyber_ollama
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.ollama.sh:/entrypoint.ollama.sh
    ports:
      - 11434:11434
    entrypoint: ["/bin/bash", "/entrypoint.ollama.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - qcyber-network
networks:
  qcyber-network:
    driver: bridge
