services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: qcyber-qml-api:v0.1
    container_name: qcyber_prod_flask_api
    restart: always
    env_file:
      - .env
    ports:
      - "${FLASK_API_PORT:?error}:${FLASK_API_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - qcyber-network
  ollama:
    profiles: ["ollama"]
    image: ollama/ollama:0.22.1
    container_name: qcyber_prod_ollama
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.ollama.sh:/entrypoint.ollama.sh
    ports:
      - ${OLLAMA_PORT:-11434}:11434
    entrypoint: ["/bin/bash", "/entrypoint.ollama.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - qcyber-network
networks:
  qcyber-network:
    name: qcyber-network
    external: true  # portanto, necessário subir serviços do backend principal inicialmente (ou apenas o mysql)
