[project]
name = "qml"
version = "0.1.0"
description = "QML - CrewAI"
authors = [{ name = "Felipe Cordeiro", email = "imfelipe.cordeiro12@gmail.com" }]
requires-python = "~=3.12.9"
dependencies = [
    "anyio>=4.10.0",
    "crewai[tools]>=0.186.1",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "flask-mysql>=1.6.0",
    "flask-mysqldb>=2.0.0",
    "gunicorn>=23.0.0",
    "joblib>=1.5.2",
    "langchain-anthropic>=0.3.20",
    "langchain-community>=0.3.29",
    "langchain-ollama==0.3.3",
    "langgraph>=0.6.7",
    "mysql>=0.0.3",
    "mysql-connector-python>=9.4.0",
    "numpy>=2.0.0",
    "pandas>=2.3.2",
    "pennylane>=0.42.3",
    "pymysql>=1.1.2",
    "python-dotenv>=1.1.1",
    "scikit-learn==1.8.0",
    "shap>=0.48.0",
]

[project.optional-dependencies]
quantum-convert = [
    "torch>=2.0.0",
]

[project.scripts]
run_crew = "qml.main:run"
run_quantum_crew = "qml.main:run_quantum"
run_rf_crew = "qml.main:run_rf"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

[dependency-groups]
dev = [
    "matplotlib>=3.10.6",
    "jupyterlab>=4.4.7",
]
